'use strict';
const sourceRange=require('./source-range');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../js/11-own-assessment.js'),'utf8');
const code=sourceRange(src,'    const myAssessmentEditHistories','    function captureMyAssessmentFocus()');
function mount(){let cp,saves=0,now=1000;const timers=new Map(),checks=[];let serial=0;class Clock extends Date{static now(){return now;}}
 const ctx={Date:Clock,getCurrentPatient:()=>cp,getMyAssessment:(p,n)=>p.myAssessments[n],ensureMyAssessment:(p,n)=>p.myAssessments[n]||(p.myAssessments[n]={}),saveMyAssessmentsSoon(){},commitMyAssessmentChange:()=>saves++,showToast(){},setTimeout:f=>{timers.set(++serial,f);return serial;},clearTimeout:id=>timers.delete(id),refreshMyAssessmentSideInfo:(p,n)=>checks.push([p.id,n])};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);return {ctx,set:p=>cp=p,saves:()=>saves,checks,tick:()=>now+=1000,run:()=>{for(const f of timers.values())f();timers.clear();},input:(n,k,v)=>ctx.onMyAssessmentInput(n,k,{value:v}),undo:n=>ctx.undoMyAssessmentEdit(n),redo:n=>ctx.undoMyAssessmentEdit(n,true)};
}
const patient=id=>({id,myAssessments:{1:{interpretation:'before',cause:'cause'},2:{interpretation:'second'}}});
test('assessment undo and redo stay separate by patient and need',()=>{const h=mount(),a=patient('a'),b=patient('b');h.set(a);h.input(1,'interpretation','after-a');h.input(2,'interpretation','after-2');h.undo(1);h.set(b);h.input(1,'interpretation','after-b');h.undo(1);h.redo(1);h.set(a);h.redo(1);assert.equal(a.myAssessments[1].interpretation,'after-a');assert.equal(a.myAssessments[2].interpretation,'after-2');assert.equal(b.myAssessments[1].interpretation,'after-b');});
test('typing groups, later edits discard redo and unrelated fields survive',()=>{const h=mount(),p=patient('p');h.set(p);h.input(1,'interpretation','a');h.input(1,'interpretation','ab');p.myAssessments[1].cause='later-cause';h.undo(1);assert.equal(p.myAssessments[1].interpretation,'before');assert.equal(p.myAssessments[1].cause,'later-cause');h.tick();h.input(1,'interpretation','new');assert.equal(h.redo(1),false);});
test('same-length external edits and deleted assessments cannot be overwritten',()=>{const h=mount(),p=patient('p');h.set(p);h.input(1,'interpretation','after');p.myAssessments[1].interpretation='other';assert.equal(h.undo(1),false);delete p.myAssessments[1];assert.equal(h.undo(1),false);assert.equal(h.saves(),0);});
test('delayed checks never switch to a different patient and timers are independent',()=>{const h=mount(),a=patient('a'),b=patient('b');h.set(a);h.input(1,'interpretation','a');h.set(b);h.input(1,'interpretation','b');h.run();assert.deepEqual(h.checks,[['b',1]]);});
