'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/12-missing-checks-and-care-plan.js'),'utf8');
const code=source.slice(source.indexOf('    const careRecordEditHistories'),source.indexOf('    function careRecordPlanState'));
function mount(){let cp,saves=0;const ctx={getCurrentPatient:()=>cp,getCarePlan:(p,id)=>p.carePlans[id]?.deleted?null:p.carePlans[id],updateCareRecord:(p,id,rid,patch)=>Object.assign(p.carePlans[id].records.find(r=>r.id===rid),patch),commitCarePlanChange:()=>saves++,showToast(){}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);return {set:p=>cp=p,edit:p=>{const r=p.carePlans.p.records[0],before=JSON.parse(JSON.stringify(r));r.evaluation='after';ctx.rememberCareRecordEdit(p,'p',before,r);},ctx,saves:()=>saves,undo:()=>ctx.undoCareRecordEdit(),redo:()=>ctx.undoCareRecordEdit(true)};}
const patient=id=>({id,carePlans:{p:{id:'p',records:[{id:'r',evaluation:'before',responseCardId:null},{id:'other',evaluation:'unrelated'}]}}});
test('record edits undo and redo independently across patients',()=>{const h=mount(),a=patient('a'),b=patient('b');h.set(a);h.edit(a);h.undo();h.set(b);h.edit(b);h.undo();h.redo();h.set(a);h.redo();assert.equal(a.carePlans.p.records[0].evaluation,'after');assert.equal(b.carePlans.p.records[0].evaluation,'after');assert.equal(h.saves(),4);});
test('updated, deleted records and deleted plans cannot be overwritten',()=>{const h=mount(),p=patient('p');h.set(p);h.edit(p);p.carePlans.p.records[0].evaluation='other';assert.equal(h.undo(),false);p.carePlans.p.records=[];assert.equal(h.undo(),false);p.carePlans.p.deleted=true;assert.equal(h.undo(),false);assert.equal(h.saves(),0);});
test('undo preserves other records and a new edit clears redo',()=>{const h=mount(),p=patient('p');h.set(p);h.edit(p);p.carePlans.p.records[1].evaluation='later';h.undo();assert.equal(p.carePlans.p.records[1].evaluation,'later');h.edit(p);assert.equal(h.redo(),false);});
test('edits creating a separate information-card link are not added to this history',()=>{const h=mount(),p=patient('p');h.set(p);const before={...p.carePlans.p.records[0]},after={...before,responseCardId:'new'};h.ctx.rememberCareRecordEdit(p,'p',before,after);assert.equal(h.undo(),false);});
const quality=require('../clinical-knowledge/patient-quality');
test('record-to-card audit detects deleted cards and changed response text',()=>{const p={id:'p',items:[{id:'c',text:'before',type:'o',hendersonIds:[1]}],carePlans:{p:{id:'p',records:[{id:'r',response:'after',responseCardId:'c'},{id:'d',response:'x',responseCardId:'missing'},{id:'deleted',deleted:true,responseCardId:'missing'}]}}};const f=quality.audit(p).findings;assert.equal(f.filter(x=>x.code==='record-response-changed').length,1);assert.equal(f.filter(x=>x.code==='record-response-missing').length,1);p.carePlans.p.records[0].response='before';assert.equal(quality.audit(p).findings.some(x=>x.code==='record-response-changed'),false);});
