'use strict';
const sourceRange=require('./source-range');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/12-missing-checks-and-care-plan.js'),'utf8');
const historySource=source.slice(source.indexOf('    const carePlanFieldHistories'),source.indexOf('    window.toggleCarePlan ='));
const inputSource=sourceRange(source,'    window.onCarePlanInput =','    window.onCarePlanProblemCommit =');
function mount(){let patient,saves=0,now=1000;class Clock extends Date { static now(){return now;} }const ctx={Date:Clock,getCurrentPatient:()=>patient,getCarePlan:(p,id)=>p.carePlans[id]?.deleted?null:p.carePlans[id],updateCarePlan:(p,id,patch)=>Object.assign(p.carePlans[id],patch),commitCarePlanChange:()=>saves++,showToast(){},CARE_PLAN_SECTIONS:[{key:'op'},{key:'tp'},{key:'ep'}],carePlanLinesToList:v=>v.split('\n'),saveMyAssessmentsSoon(){},document:{querySelector:()=>null}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(historySource+'\n'+inputSource,ctx);return {ctx,set:p=>patient=p,tick:()=>now+=1000,saves:()=>saves,input:(key,value)=>ctx.onCarePlanInput('plan',key,{value}),undo:()=>ctx.undoCarePlanField(),redo:()=>ctx.undoCarePlanField(true)};}
const patient=id=>({id,carePlans:{plan:{id:'plan',goalShort:'before',op:['old'],status:'active'}}});
test('actual care plan input supports patient-specific undo and redo',()=>{const h=mount(),a=patient('a'),b=patient('b');h.set(a);h.input('goalShort','after-a');h.undo();h.set(b);h.input('goalShort','after-b');h.undo();h.redo();h.set(a);h.redo();assert.equal(a.carePlans.plan.goalShort,'after-a');assert.equal(b.carePlans.plan.goalShort,'after-b');assert.equal(h.saves(),4);});
test('typing is grouped and new edits discard redo',()=>{const h=mount(),p=patient('p');h.set(p);h.input('goalShort','a');h.input('goalShort','ab');h.undo();assert.equal(p.carePlans.plan.goalShort,'before');h.tick();h.input('goalShort','later');assert.equal(h.redo(),false);assert.equal(p.carePlans.plan.goalShort,'later');});
test('same-length external changes and deleted plans block undo',()=>{const h=mount(),p=patient('p');h.set(p);h.input('goalShort','after');p.carePlans.plan.goalShort='other';assert.equal(h.undo(),false);assert.equal(p.carePlans.plan.goalShort,'other');p.carePlans.plan.deleted=true;assert.equal(h.undo(),false);assert.equal(h.saves(),0);});
test('undo restores only the edited field and preserves later changes elsewhere',()=>{const h=mount(),p=patient('p');h.set(p);h.input('op','first\nsecond');p.carePlans.plan.status='finished';h.undo();assert.deepEqual(JSON.parse(JSON.stringify(p.carePlans.plan.op)),['old']);assert.equal(p.carePlans.plan.status,'finished');assert.equal(p.carePlans.plan.userEdited,true);});
